In [3]:
!pip install statsbombpy

Collecting statsbombpy
  Downloading statsbombpy-1.22.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 5.3 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.32.4)
Collecting requests-cache (from statsbombpy)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: inflect in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (1.6.0)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (4.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->statsbombpy) (3.1.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache->statsbombpy)
  Downloading cattrs-26.2.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (4.11.7)
Collecting url-normalize>=2.0 (from requests-cache->statsbombpy)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Downloading statsbombpy-1.22.0-py3-none-any.whl (18 kB)
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 5.8 MB/s eta 0:00:00
Downloading cattrs-26.2.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 5.9 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, statsbombpy
Successfully installed cattrs-26.2.0 requests-cache-1.3.3 statsbombpy-1.22.0 url-normalize-3.0.0

In [4]:
import pandas as pd
from statsbombpy import sb

In [5]:
competitions = sb.competitions()
competitions

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2026-04-11T12:48:10.012987,2021-06-13T16:17:31.694,None,2026-04-11T12:48:10.012987
76,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2026-04-27T22:02:42.690507,2026-04-27T22:03:28.087062,2026-04-27T22:03:28.087062,2026-04-27T22:02:42.690507
77,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2026-05-05T03:03:04.199896,2026-05-05T03:05:32.480837,2026-05-05T03:05:32.480837,2026-05-05T03:03:04.199896
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,None,2026-05-15T15:31:40.299642

In [6]:
la_liga_2020_2021 = competitions[(competitions['competition_name'] == 'La Liga') & (competitions['season_name'] == '2020/2021')]
la_liga_2020_2021

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
40,11,90,Spain,La Liga,male,False,False,2020/2021,2025-11-02T03:55:19.577958,2025-11-02T03:55:53.923193,2025-11-02T03:55:53.923193,2025-11-02T03:55:19.577958

In [11]:
la_liga_2020_2021_matches = sb.matches(competition_id=la_liga_2020_2021['competition_id'].iloc[0], season_id=la_liga_2020_2021['season_id'].iloc[0])
la_liga_2020_2021_matches

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3773386,2020-10-31,21:00:00.000,1,1,available,available,2023-07-25T03:54:59.280826,2023-07-25T04:25:41.348202,8,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
1,3773565,2021-01-09,18:30:00.000,0,4,available,available,2023-07-25T03:51:37.437064,2023-07-25T04:30:16.058384,18,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
2,3773457,2021-05-16,18:30:00.000,1,2,available,available,2022-12-02T09:26:39.496362,2023-04-27T23:03:53.506485,37,...,Netherlands,2886,Eduardo Germán Coudet,Eduardo Coudet,1974-09-12,11,Argentina,1.1.0,2,2
3,3773631,2021-02-07,21:00:00.000,2,3,available,available,2023-07-25T03:47:44.278651,2023-07-25T03:56:34.733180,22,...,Chile,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
4,3773665,2021-03-06,21:00:00.000,0,2,available,available,2022-12-02T08:46:42.897589,2023-04-28T02:57:03.412841,26,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
5,3773497,2021-04-10,21:00:00.000,2,1,available,available,2022-12-02T09:04:21.859831,2023-04-28T01:35:16.051381,30,...,France,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
6,3773660,2020-12-13,21:00:00.000,1,0,available,available,2022-12-01T14:49:02.748131,2023-04-28T06:01:10.173360,13,...,Netherlands,219,Francisco José López Fernández,Paco López,1967-09-19,214,Spain,1.1.0,2,2
7,3773593,2020-09-27,21:00:00.000,4,0,available,available,2023-07-25T04:01:57.790373,2023-07-25T04:44:03.367478,3,...,Netherlands,21,Unai Emery Etxegoien,Unai Emery,1971-11-03,214,Spain,1.1.0,2,2
8,3773466,2020-10-01,21:30:00.000,0,3,available,available,2023-07-25T03:55:25.794505,2023-07-25T04:40:53.635540,4,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
9,3773585,2020-10-24,16:00:00.000,1,3,available,available,2023-07-25T03:53:35.185506,2023-07-25T04:29:21.140321,7,...,Netherlands,56,Zinédine Zidane,None,1972-06-23,78,France,1.1.0,2,2
10,3773552,2021-01-03,21:00:00.000,0,1,available,available,2021-05-09T12:03:31.185940,2022-08-04T12:00,17,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
11,3773672,2020-10-04,21:00:00.000,1,1,available,available,2023-07-25T03:58:44.264327,2023-07-25T04:37:23.452819,5,...,Netherlands,741,Julen Lopetegui Argote,Julen Lopetegui,1966-08-28,214,Spain,1.1.0,2,2
12,3773587,2020-10-17,21:00:00.000,1,0,available,available,2023-07-25T04:01:45.160583,2023-07-25T04:34:28.413719,6,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
13,3773656,2020-11-21,21:00:00.000,1,0,available,available,2020-11-24T06:29:13.401420,2022-08-04T12:00,10,...,Argentina,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
14,3773377,2020-12-19,16:15:00.000,2,2,available,available,2023-07-25T03:50:34.381454,2023-07-25T03:51:52.970329,14,...,Netherlands,188,Javier Gracia Carlos,Javi Gracia,1970-05-01,214,Spain,1.1.0,2,2
15,3773586,2021-04-29,19:00:00.000,1,2,available,available,2021-07-06T16:43:21.218,2022-08-04T12:00,33,...,Netherlands,1597,Diego Martínez Penas,None,1980-12-16,214,Spain,1.1.0,2,2
16,3773372,2021-05-08,16:15:00.000,0,0,available,available,2021-05-10T04:24:10.396826,2022-08-04T12:00,35,...,Netherlands,230,Diego Pablo Simeone,Diego Simeone,1970-04-28,11,Argentina,1.1.0,2,2
17,3773387,2021-05-11,22:00:00.000,3,3,available,available,2021-05-13T00:20:44.739341,2022-08-04T12:00,36,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
18,3773695,2021-05-02,21:00:00.000,2,3,available,available,2021-05-07T13:24:24.423335,2022-08-04T12:00,34,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
19,3773369,2021-03-15,21:00:00.000,4,1,available,available,2022-12-02T08:56:56.809012,2023-04-28T02:22:22.114288,27,...,Netherlands,1605,Juan José Rojo Martín,Pacheta,1968-03-23,214,Spain,1.1.0,2,2
20,3773661,2021-04-22,22:00:00.000,5,2,available,available,2021-04-23T20:17:32.331635,2022-08-04T12:00,31,...,Netherlands,228,José Bordalás Jiménez,Pepe Bordalás,1964-03-05,214,Spain,1.1.0,2,2
21,3773597,2021-03-21,21:00:00.000,1,6,available,available,2021-03-22T21:28:32.452567,2022-08-04T12:00,28,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
22,3773523,2020-12-16,21:00:00.000,2,1,available,available,2023-07-25T03:54:28.731114,2023-07-25T04:40:11.813772,19,...,Netherlands,85,Imanol Alguacil Barrenetxea,Imanol Alguacil,1971-07-04,214,Spain,1.1.0,2,2
23,3773571,2020-12-22,22:00:00.000,0,3,available,available,2022-12-01T14:54:17.777866,2023-04-28T05:40:41.883197,15,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
24,3773428,2020-12-05,21:00:00.000,2,1,available,available,2023-07-25T03:50:55.226757,2023-07-25T04:44:09.299901,12,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
25,3764661,2021-01-06,21:00:00.000,2,3,available,available,2021-05-07T04:07:28.081860,2022-08-04T12:00,2,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
26,3773526,2021-02-13,21:00:00.000,5,1,available,available,2023-07-25T03:50:51.336686,2023-07-25T04:23:57.898904,23,...,Netherlands,187,Abelardo Fernández Antuña,Abelardo,1970-04-19,214,Spain,1.1.0,2,2
27,3773474,2021-04-05,21:00:00.000,1,0,available,available,2021-04-12T07:10:50.227712,2022-08-04T12:00,29,...,Netherlands,576,Sergio González Soriano,Sergio,1976-11-10,214,Spain,1.1.0,2,2
28,3773625,2021-02-27,16:15:00.000,0,2,available,available,2021-11-28T09:47:02.505122,2022-08-04T12:00,25,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
29,3773403,2021-01-31,21:00:00.000,2,1,available,available,2022-12-02T08:36:08.592852,2023-04-28T08:16:45.884638,21,...,Netherlands,211,Marcelino García Toral,Marcelino,1965-08-14,214,Spain,1.1.0,2,2
30,3773547,2020-11-29,14:00:00.000,4,0,available,available,2020-11-30T09:14:36.663981,2022-08-04T12:00,11,...,Netherlands,1592,Jagoba Arrasate Elustondo,Jagoba Arrasate,1978-04-22,214,Spain,1.1.0,2,2
31,3773415,2021-02-21,14:00:00.000,1,1,available,available,2023-07-25T03:10:18.051218,2023-07-25T03:17:10.679932,24,...,Netherlands,1598,Álvaro Cervera Díaz,Álvaro Cervera,1965-09-20,214,Spain,1.1.0,2,2
32,3764440,2021-02-24,19:00:00.000,3,0,available,available,2023-07-25T03:06:46.373172,2023-07-25T03:12:39.582957,1,...,Netherlands,509,Francisco Escriba Segura,Fran Escribá,1965-05-03,214,Spain,1.1.0,2,2
33,3773689,2021-04-25,16:15:00.000,1,2,available,available,2022-12-02T09:12:52.250855,2023-04-28T00:44:33.357677,32,...,Spain,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
34,3773477,2020-11-07,16:15:00.000,5,2,available,available,2023-07-25T03:59:53.393191,2023-07-25T04:21:10.335828,9,...,Netherlands,733,Manuel Luis Pellegrini Ripamonti,Manuel Pellegrini,1953-09-16,45,Chile,1.1.0,2,2

In [18]:
la_liga_2020_2021_matches[['home_team', 'away_team']]

           home_team         away_team
0   Deportivo Alavés         Barcelona
1            Granada         Barcelona
2          Barcelona        Celta Vigo
3         Real Betis         Barcelona
4            Osasuna         Barcelona
5        Real Madrid         Barcelona
6          Barcelona        Levante UD
7          Barcelona        Villarreal
8         Celta Vigo         Barcelona
9          Barcelona       Real Madrid
10            Huesca         Barcelona
11         Barcelona           Sevilla
12            Getafe         Barcelona
13   Atlético Madrid         Barcelona
14         Barcelona          Valencia
15         Barcelona           Granada
16         Barcelona   Atlético Madrid
17        Levante UD         Barcelona
18          Valencia         Barcelona
19         Barcelona            Huesca
20         Barcelona            Getafe
21     Real Sociedad         Barcelona
22         Barcelona     Real Sociedad
23   Real Valladolid         Barcelona
24             Cádiz         Barcelona
25     Athletic Club         Barcelona
26         Barcelona  Deportivo Alavés
27         Barcelona   Real Valladolid
28           Sevilla         Barcelona
29         Barcelona     Athletic Club
30         Barcelona           Osasuna
31         Barcelona             Cádiz
32         Barcelona             Elche
33        Villarreal         Barcelona
34         Barcelona        Real Betis

In [13]:
la_liga_2020_2021_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 55 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   match_id                   35 non-null     int64
 1   match_date                 35 non-null     object
 2   kick_off                   35 non-null     object
 3   home_score                 35 non-null     int64
 4   away_score                 35 non-null     int64
 5   match_status               35 non-null     object
 6   match_status_360           35 non-null     object
 7   last_updated               35 non-null     object
 8   last_updated_360           35 non-null     object
 9   match_week                 35 non-null     int64
 10  competition_id             35 non-null     int64
 11  competition_country_name   35 non-null     object
 12  competition_name           35 non-null     object
 13  competition                35 non-null     object
 14  season_id                  35 non-null     int64
 15  season                     35 non-null     object
 16  home_team_id               35 non-null     int64
 17  home_team                  35 non-null     object
 18  home_team_gender           35 non-null     object
 19  home_team_group            0 non-null      object
 20  home_team_country_id       35 non-null     int64
 21  home_team_country_name     35 non-null     object
 22  away_team_id               35 non-null     int64
 23  away_team                  35 non-null     object
 24  away_team_gender           35 non-null     object
 25  away_team_group            0 non-null      object
 26  away_team_country_id       35 non-null     int64
 27  away_team_country_name     35 non-null     object
 28  competition_stage_id       35 non-null     int64
 29  competition_stage          35 non-null     object
 30  stadium_id                 35 non-null     int64
 31  stadium                    35 non-null     object
 32  stadium_country_id         35 non-null     int64
 33  stadium_country_name       35 non-null     object
 34  referee_id                 30 non-null     float64
 35  referee                    30 non-null     object
 36  referee_country_id         30 non-null     float64
 37  referee_country_name       30 non-null     object
 38  home_managers              35 non-null     object
 39  away_managers              35 non-null     object
 40  home_manager_id            35 non-null     int64
 41  home_manager_name          35 non-null     object
 42  home_manager_nickname      15 non-null     object
 43  home_manager_dob           35 non-null     object
 44  home_manager_country_id    35 non-null     int64
 45  home_manager_country_name  35 non-null     object
 46  away_manager_id            35 non-null     int64
 47  away_manager_name          35 non-null     object
 48  away_manager_nickname      16 non-null     object
 49  away_manager_dob           35 non-null     object
 50  away_manager_country_id    35 non-null     int64
 51  away_manager_country_name  35 non-null     object
 52  data_version               35 non-null     object
 53  shot_fidelity_version      35 non-null     object
 54  xy_fidelity_version        35 non-null     object
dtypes: float64(2), int64(17), object(36)
memory usage: 15.2+ KB

In [22]:
el_classicos = la_liga_2020_2021_matches[((la_liga_2020_2021_matches['away_team'] == 'Barcelona') & (la_liga_2020_2021_matches['home_team'] == 'Real Madrid')) | ((la_liga_2020_2021_matches['home_team'] == 'Barcelona') & (la_liga_2020_2021_matches['away_team'] == 'Real Madrid'))]
el_classicos

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
5,3773497,2021-04-10,21:00:00.000,2,1,available,available,2022-12-02T09:04:21.859831,2023-04-28T01:35:16.051381,30,...,France,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
9,3773585,2020-10-24,16:00:00.000,1,3,available,available,2023-07-25T03:53:35.185506,2023-07-25T04:29:21.140321,7,...,Netherlands,56,Zinédine Zidane,None,1972-06-23,78,France,1.1.0,2,2

In [23]:
el_classico = sb.events(match_id=el_classicos['match_id'].iloc[0])
el_classico

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4141, 'lineup': [{'player': {'id...",Real Madrid,220,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 343, 'lineup': [{'player': {'id'...",Barcelona,217,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:00:00.000,Half Start,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:49:06.547,Half End,NaN
3987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 352, 'lineup': [{'player': {'id'...",Barcelona,217,00:04:31.063,Tactical Shift,NaN
3988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 352, 'lineup': [{'player': {'id'...",Barcelona,217,00:35:42.006,Tactical Shift,NaN
3989,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:38:40.583,Bad Behaviour,NaN
3990,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:49:05.892,Bad Behaviour,NaN

In [24]:
el_classico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3991 entries, 0 to 3990
Data columns (total 94 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   bad_behaviour_card              2 non-null      object
 1   ball_receipt_outcome            108 non-null    object
 2   ball_recovery_offensive         1 non-null      object
 3   ball_recovery_recovery_failure  5 non-null      object
 4   block_deflection                1 non-null      object
 5   block_offensive                 2 non-null      object
 6   carry_end_location              971 non-null    object
 7   clearance_aerial_won            4 non-null      object
 8   clearance_body_part             32 non-null     object
 9   clearance_head                  11 non-null     object
 10  clearance_left_foot             7 non-null      object
 11  clearance_right_foot            14 non-null     object
 12  counterpress                    110 non-null    object
 13  dribble_nutmeg                  2 non-null      object
 14  dribble_outcome                 41 non-null     object
 15  dribble_overrun                 2 non-null      object
 16  duel_outcome                    33 non-null     object
 17  duel_type                       51 non-null     object
 18  duration                        2948 non-null   float64
 19  foul_committed_advantage        2 non-null      object
 20  foul_committed_card             5 non-null      object
 21  foul_committed_offensive        1 non-null      object
 22  foul_committed_type             3 non-null      object
 23  foul_won_advantage              2 non-null      object
 24  foul_won_defensive              3 non-null      object
 25  goalkeeper_body_part            5 non-null      object
 26  goalkeeper_end_location         25 non-null     object
 27  goalkeeper_outcome              10 non-null     object
 28  goalkeeper_position             32 non-null     object
 29  goalkeeper_technique            7 non-null      object
 30  goalkeeper_type                 35 non-null     object
 31  id                              3991 non-null   object
 32  index                           3991 non-null   int64
 33  interception_outcome            20 non-null     object
 34  location                        3966 non-null   object
 35  match_id                        3991 non-null   int64
 36  minute                          3991 non-null   int64
 37  miscontrol_aerial_won           1 non-null      object
 38  off_camera                      47 non-null     object
 39  out                             35 non-null     object
 40  pass_aerial_won                 12 non-null     object
 41  pass_angle                      1103 non-null   float64
 42  pass_assisted_shot_id           20 non-null     object
 43  pass_body_part                  1050 non-null   object
 44  pass_cross                      22 non-null     object
 45  pass_deflected                  1 non-null      object
 46  pass_end_location               1103 non-null   object
 47  pass_goal_assist                2 non-null      object
 48  pass_height                     1103 non-null   object
 49  pass_inswinging                 2 non-null      object
 50  pass_length                     1103 non-null   float64
 51  pass_miscommunication           2 non-null      object
 52  pass_no_touch                   4 non-null      object
 53  pass_outcome                    168 non-null    object
 54  pass_outswinging                2 non-null      object
 55  pass_recipient                  1043 non-null   object
 56  pass_recipient_id               1043 non-null   float64
 57  pass_shot_assist                18 non-null     object
 58  pass_straight                   4 non-null      object
 59  pass_switch                     19 non-null     object
 60  pass_technique                  20 non-null     object
 61  pass_through_ball               12 non-null     object
 62  pass_type                       167 non-null    object
 63  period                          3991 non-null   int64
 64  play_pattern                    3991 non-null   object
 65  player                          3979 non-null   object
 66  player_id                       3979 non-null   float64
 67  position                        3979 non-null   object
 68  possession                      3991 non-null   int64
 69  possession_team                 3991 non-null   object
 70  possession_team_id              3991 non-null   int64
 71  related_events                  3856 non-null   object
 72  second                          3991 non-null   int64
 73  shot_aerial_won                 1 non-null      object
 74  shot_body_part                  32 non-null     object
 75  shot_deflected                  1 non-null      object
 76  shot_end_location               32 non-null     object
 77  shot_first_time                 14 non-null     object
 78  shot_freeze_frame               32 non-null     object
 79  shot_key_pass_id                20 non-null     object
 80  shot_outcome                    32 non-null     object
 81  shot_statsbomb_xg               32 non-null     float64
 82  shot_technique                  32 non-null     object
 83  shot_type                       32 non-null     object
 84  substitution_outcome            10 non-null     object
 85  substitution_outcome_id         10 non-null     float64
 86  substitution_replacement        10 non-null     object
 87  substitution_replacement_id     10 non-null     float64
 88  tactics                         4 non-null      object
 89  team                            3991 non-null   object
 90  team_id                         3991 non-null   int64
 91  timestamp                       3991 non-null   object
 92  type                            3991 non-null   object
 93  under_pressure                  788 non-null    object
dtypes: float64(8), int64(8), object(78)
memory usage: 2.9+ MB

In [26]:
el_classico_shots = el_classico[el_classico['type'] == 'Shot']
el_classico_shots

,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
3940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:09:14.816,Shot,NaN
3941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:12:58.955,Shot,NaN
3942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:15:28.083,Shot,True
3943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:20:16.021,Shot,NaN
3944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:23:11.513,Shot,NaN
3945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:27:06.449,Shot,NaN
3946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:33:49.727,Shot,NaN
3947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:33:51.417,Shot,NaN
3948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:34:36.417,Shot,NaN
3949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:34:37.931,Shot,NaN
3950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:36:07.631,Shot,NaN
3951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:40:42.624,Shot,NaN
3952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:44:50.325,Shot,NaN
3953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:47:07.510,Shot,NaN
3954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:02:24.662,Shot,NaN
3955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:07:44.030,Shot,NaN
3956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:11:21.815,Shot,NaN
3957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:14:09.045,Shot,NaN
3958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:19:04.774,Shot,NaN
3959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:22:40.960,Shot,NaN
3960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:24:31.072,Shot,NaN
3961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:25:29.887,Shot,True
3962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:29:23.268,Shot,NaN
3963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:31:06.634,Shot,NaN
3964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:31:09.259,Shot,NaN
3965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,220,00:36:31.229,Shot,NaN
3966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:45:34.224,Shot,NaN
3967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:46:22.766,Shot,True
3968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:47:39.245,Shot,NaN
3969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:48:53.830,Shot,True
3970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:48:56.040,Shot,NaN
3971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:48:58.690,Shot,NaN

# Przydatne:
1. Period (informuje o momencie meczu 1 - pierwsza połowa, 2 - druga połowa) : Int
2. position (pozycja, na której gra zawodnik wykonujący akcję) : String
3. location (pozycja strzału) : [x, y]
4. play pattern (rodzaj zagrania, z którego wyniknął strzał np. rzut wolny, atak pozycyjny) : String
5. under_pressure (informacja czy zawodnik był presowany przez obrońcę) : True/NaN
6. shot_outcome - LABEL, INFORMACJA CZY BYŁ GOL : String (np. Post, Goal)
7. shot_type (rodzaj strzału np. atak pozycyjny, rzut wolny) : String
8. shot_body_part (część ciała, którą oddano strzał) : String
9. shot_technique (technika wykonania strzału np. wolej, strzał po ziemi) : String
10. shot_first_time (czy strzał z pierwszej) : True/Nan
11. shot_deflected (czy był rykoszet) : True/Nan
12. shot_freeze_frame (koordynaty wszystkich zawodników) : lista słownikowa zawodników i lokacji
13. shot_aerial_won (czy zawodnik musiał wygrać pozycję do główki) : True/NaN

# Warte uwagi:
1. timestamp (może dodać dużo kontekstu [szarałt dla Legii]) : String
2. related_events (eventy które doprowadziły do strzału) : lista Stringów
3. shot_key_pass_id (id kluczowego podania dla danego strzału) : String/Nan

In [54]:
el_classico_clean = el_classico_shots[['period', 'position', 'location', 'play_pattern', 'under_pressure', 'shot_outcome', 'shot_type', 'shot_body_part', 'shot_technique', 'shot_first_time', 'shot_deflected', 'shot_freeze_frame', 'shot_aerial_won']]
el_classico_clean

,period,position,location,play_pattern,under_pressure,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_deflected,shot_freeze_frame,shot_aerial_won
3940,1,Right Center Back,"[101.9, 58.1]",Regular Play,NaN,Off T,Open Play,Right Foot,Normal,NaN,NaN,"[{'location': [117.5, 42.5], 'player': {'id': ...",NaN
3941,1,Center Forward,"[113.8, 45.4]",Regular Play,NaN,Goal,Open Play,Right Foot,Backheel,True,NaN,"[{'location': [111.3, 59.9], 'player': {'id': ...",NaN
3942,1,Center Forward,"[116.1, 38.6]",From Throw In,True,Wayward,Open Play,Head,Normal,NaN,NaN,"[{'location': [110.4, 33.0], 'player': {'id': ...",True
3943,1,Right Center Midfield,"[103.1, 35.5]",Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [102.5, 36.9], 'player': {'id': ...",NaN
3944,1,Center Forward,"[90.9, 34.5]",From Free Kick,NaN,Off T,Free Kick,Right Foot,Normal,NaN,NaN,"[{'location': [117.6, 39.9], 'player': {'id': ...",NaN
3945,1,Left Center Midfield,"[101.0, 27.2]",From Free Kick,NaN,Goal,Free Kick,Right Foot,Normal,NaN,True,"[{'location': [109.5, 31.7], 'player': {'id': ...",NaN
3946,1,Right Midfield,"[107.3, 53.4]",Regular Play,NaN,Post,Open Play,Right Foot,Normal,NaN,NaN,"[{'location': [108.0, 38.9], 'player': {'id': ...",NaN
3947,1,Right Back,"[105.9, 42.4]",Regular Play,NaN,Saved,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [115.9, 43.7], 'player': {'id': ...",NaN
3948,1,Right Midfield,"[96.2, 47.9]",From Corner,NaN,Blocked,Open Play,Right Foot,Volley,True,NaN,"[{'location': [95.2, 34.6], 'player': {'id': 5...",NaN
3949,1,Right Center Back,"[108.6, 41.4]",From Corner,NaN,Blocked,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [106.7, 34.2], 'player': {'id': ...",NaN
3950,1,Center Forward,"[94.9, 46.8]",Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [105.2, 50.4], 'player': {'id': ...",NaN
3951,1,Right Wing,"[99.8, 33.8]",Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [102.8, 32.4], 'player': {'id': ...",NaN
3952,1,Right Wing,"[112.8, 24.6]",From Throw In,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [108.0, 45.9], 'player': {'id': ...",NaN
3953,1,Right Wing,"[117.0, 47.2]",From Corner,NaN,Saved,Open Play,Left Foot,Half Volley,NaN,NaN,"[{'location': [118.5, 38.1], 'player': {'id': ...",NaN
3954,2,Right Wing,"[114.1, 32.7]",Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,True,NaN,"[{'location': [108.1, 27.5], 'player': {'id': ...",NaN
3955,2,Left Center Midfield,"[93.8, 41.8]",Regular Play,NaN,Off T,Open Play,Right Foot,Normal,True,NaN,"[{'location': [96.5, 51.4], 'player': {'id': 8...",NaN
3956,2,Center Forward,"[101.3, 30.6]",Regular Play,NaN,Off T,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [98.8, 41.7], 'player': {'id': 5...",NaN
3957,2,Right Center Back,"[110.6, 39.8]",Regular Play,NaN,Goal,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [111.9, 43.1], 'player': {'id': ...",NaN
3958,2,Right Center Forward,"[90.5, 35.5]",From Free Kick,NaN,Blocked,Free Kick,Left Foot,Normal,NaN,NaN,"[{'location': [99.6, 34.9], 'player': {'id': 5...",NaN
3959,2,Left Center Midfield,"[112.2, 43.1]",From Free Kick,NaN,Wayward,Open Play,Head,Normal,NaN,NaN,"[{'location': [117.6, 39.8], 'player': {'id': ...",NaN
3960,2,Right Center Forward,"[97.2, 34.9]",From Free Kick,NaN,Blocked,Free Kick,Left Foot,Normal,NaN,NaN,"[{'location': [106.7, 36.6], 'player': {'id': ...",NaN
3961,2,Right Center Back,"[113.6, 56.5]",Regular Play,True,Wayward,Open Play,Right Foot,Normal,NaN,NaN,"[{'location': [109.4, 33.0], 'player': {'id': ...",NaN
3962,2,Center Back,"[112.1, 32.9]",From Throw In,NaN,Saved,Open Play,Head,Normal,NaN,NaN,"[{'location': [112.3, 34.2], 'player': {'id': ...",NaN
3963,2,Left Center Midfield,"[103.6, 40.4]",From Corner,NaN,Blocked,Open Play,Right Foot,Normal,True,NaN,"[{'location': [105.6, 55.9], 'player': {'id': ...",NaN
3964,2,Left Midfield,"[102.2, 29.5]",From Corner,NaN,Off T,Open Play,Left Foot,Half Volley,True,NaN,"[{'location': [101.4, 50.2], 'player': {'id': ...",NaN
3965,2,Left Center Midfield,"[102.3, 49.2]",From Throw In,NaN,Off T,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [111.4, 39.5], 'player': {'id': ...",NaN
3966,2,Right Center Forward,"[98.3, 52.5]",From Free Kick,NaN,Saved,Free Kick,Left Foot,Normal,NaN,NaN,"[{'location': [106.5, 36.0], 'player': {'id': ...",NaN
3967,2,Center Back,"[101.3, 29.1]",From Goal Kick,True,Off T,Open Play,Right Foot,Normal,True,NaN,"[{'location': [102.9, 48.1], 'player': {'id': ...",NaN
3968,2,Left Center Forward,"[109.4, 31.2]",Regular Play,NaN,Off T,Open Play,Head,Normal,NaN,NaN,"[{'location': [117.7, 38.1], 'player': {'id': ...",NaN
3969,2,Center Back,"[108.1, 39.1]",From Free Kick,True,Blocked,Open Play,Right Foot,Volley,True,NaN,"[{'location': [99.1, 43.4], 'player': {'id': 2...",NaN
3970,2,Goalkeeper,"[102.0, 41.1]",From Free Kick,NaN,Blocked,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [94.9, 40.2], 'player': {'id': 5...",NaN
3971,2,Left Wing Back,"[100.6, 33.2]",From Free Kick,NaN,Off T,Open Play,Left Foot,Volley,True,NaN,"[{'location': [107.7, 35.9], 'player': {'id': ...",NaN

In [62]:
location = el_classico_clean['location']
x_position = []
y_position = []
for location in location:
  x_position.append(location[0])
  y_position.append(location[1])

el_classico_clean.loc[:, 'location_x'] = x_position
el_classico_clean.loc[:, 'location_y'] = y_position
el_classico_clean = el_classico_clean.drop(columns=['location'])
el_classico_clean

,period,position,play_pattern,under_pressure,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_deflected,shot_freeze_frame,shot_aerial_won,location_x,location_y
3940,1,Right Center Back,Regular Play,NaN,Off T,Open Play,Right Foot,Normal,NaN,NaN,"[{'location': [117.5, 42.5], 'player': {'id': ...",NaN,101.9,58.1
3941,1,Center Forward,Regular Play,NaN,Goal,Open Play,Right Foot,Backheel,True,NaN,"[{'location': [111.3, 59.9], 'player': {'id': ...",NaN,113.8,45.4
3942,1,Center Forward,From Throw In,True,Wayward,Open Play,Head,Normal,NaN,NaN,"[{'location': [110.4, 33.0], 'player': {'id': ...",True,116.1,38.6
3943,1,Right Center Midfield,Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [102.5, 36.9], 'player': {'id': ...",NaN,103.1,35.5
3944,1,Center Forward,From Free Kick,NaN,Off T,Free Kick,Right Foot,Normal,NaN,NaN,"[{'location': [117.6, 39.9], 'player': {'id': ...",NaN,90.9,34.5
3945,1,Left Center Midfield,From Free Kick,NaN,Goal,Free Kick,Right Foot,Normal,NaN,True,"[{'location': [109.5, 31.7], 'player': {'id': ...",NaN,101.0,27.2
3946,1,Right Midfield,Regular Play,NaN,Post,Open Play,Right Foot,Normal,NaN,NaN,"[{'location': [108.0, 38.9], 'player': {'id': ...",NaN,107.3,53.4
3947,1,Right Back,Regular Play,NaN,Saved,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [115.9, 43.7], 'player': {'id': ...",NaN,105.9,42.4
3948,1,Right Midfield,From Corner,NaN,Blocked,Open Play,Right Foot,Volley,True,NaN,"[{'location': [95.2, 34.6], 'player': {'id': 5...",NaN,96.2,47.9
3949,1,Right Center Back,From Corner,NaN,Blocked,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [106.7, 34.2], 'player': {'id': ...",NaN,108.6,41.4
3950,1,Center Forward,Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [105.2, 50.4], 'player': {'id': ...",NaN,94.9,46.8
3951,1,Right Wing,Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [102.8, 32.4], 'player': {'id': ...",NaN,99.8,33.8
3952,1,Right Wing,From Throw In,NaN,Blocked,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [108.0, 45.9], 'player': {'id': ...",NaN,112.8,24.6
3953,1,Right Wing,From Corner,NaN,Saved,Open Play,Left Foot,Half Volley,NaN,NaN,"[{'location': [118.5, 38.1], 'player': {'id': ...",NaN,117.0,47.2
3954,2,Right Wing,Regular Play,NaN,Blocked,Open Play,Left Foot,Normal,True,NaN,"[{'location': [108.1, 27.5], 'player': {'id': ...",NaN,114.1,32.7
3955,2,Left Center Midfield,Regular Play,NaN,Off T,Open Play,Right Foot,Normal,True,NaN,"[{'location': [96.5, 51.4], 'player': {'id': 8...",NaN,93.8,41.8
3956,2,Center Forward,Regular Play,NaN,Off T,Open Play,Left Foot,Normal,NaN,NaN,"[{'location': [98.8, 41.7], 'player': {'id': 5...",NaN,101.3,30.6
3957,2,Right Center Back,Regular Play,NaN,Goal,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [111.9, 43.1], 'player': {'id': ...",NaN,110.6,39.8
3958,2,Right Center Forward,From Free Kick,NaN,Blocked,Free Kick,Left Foot,Normal,NaN,NaN,"[{'location': [99.6, 34.9], 'player': {'id': 5...",NaN,90.5,35.5
3959,2,Left Center Midfield,From Free Kick,NaN,Wayward,Open Play,Head,Normal,NaN,NaN,"[{'location': [117.6, 39.8], 'player': {'id': ...",NaN,112.2,43.1
3960,2,Right Center Forward,From Free Kick,NaN,Blocked,Free Kick,Left Foot,Normal,NaN,NaN,"[{'location': [106.7, 36.6], 'player': {'id': ...",NaN,97.2,34.9
3961,2,Right Center Back,Regular Play,True,Wayward,Open Play,Right Foot,Normal,NaN,NaN,"[{'location': [109.4, 33.0], 'player': {'id': ...",NaN,113.6,56.5
3962,2,Center Back,From Throw In,NaN,Saved,Open Play,Head,Normal,NaN,NaN,"[{'location': [112.3, 34.2], 'player': {'id': ...",NaN,112.1,32.9
3963,2,Left Center Midfield,From Corner,NaN,Blocked,Open Play,Right Foot,Normal,True,NaN,"[{'location': [105.6, 55.9], 'player': {'id': ...",NaN,103.6,40.4
3964,2,Left Midfield,From Corner,NaN,Off T,Open Play,Left Foot,Half Volley,True,NaN,"[{'location': [101.4, 50.2], 'player': {'id': ...",NaN,102.2,29.5
3965,2,Left Center Midfield,From Throw In,NaN,Off T,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [111.4, 39.5], 'player': {'id': ...",NaN,102.3,49.2
3966,2,Right Center Forward,From Free Kick,NaN,Saved,Free Kick,Left Foot,Normal,NaN,NaN,"[{'location': [106.5, 36.0], 'player': {'id': ...",NaN,98.3,52.5
3967,2,Center Back,From Goal Kick,True,Off T,Open Play,Right Foot,Normal,True,NaN,"[{'location': [102.9, 48.1], 'player': {'id': ...",NaN,101.3,29.1
3968,2,Left Center Forward,Regular Play,NaN,Off T,Open Play,Head,Normal,NaN,NaN,"[{'location': [117.7, 38.1], 'player': {'id': ...",NaN,109.4,31.2
3969,2,Center Back,From Free Kick,True,Blocked,Open Play,Right Foot,Volley,True,NaN,"[{'location': [99.1, 43.4], 'player': {'id': 2...",NaN,108.1,39.1
3970,2,Goalkeeper,From Free Kick,NaN,Blocked,Open Play,Right Foot,Half Volley,True,NaN,"[{'location': [94.9, 40.2], 'player': {'id': 5...",NaN,102.0,41.1
3971,2,Left Wing Back,From Free Kick,NaN,Off T,Open Play,Left Foot,Volley,True,NaN,"[{'location': [107.7, 35.9], 'player': {'id': ...",NaN,100.6,33.2

In [66]:
shot_aerial_won = (el_classico_clean['shot_aerial_won'] == True).astype(int)
shot_deflected = (el_classico_clean['shot_deflected'] == True).astype(int)
shot_first_time = (el_classico_clean['shot_first_time'] == True).astype(int)
under_pressure = (el_classico_clean['under_pressure'] == True).astype(int)
el_classico_clean.loc[:, 'shot_aerial_won'] = shot_aerial_won
el_classico_clean.loc[:, 'shot_deflected'] = shot_deflected
el_classico_clean.loc[:, 'shot_first_time'] = shot_first_time
el_classico_clean.loc[:, 'under_pressure'] = under_pressure
el_classico_clean

,period,position,play_pattern,under_pressure,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_deflected,shot_freeze_frame,shot_aerial_won,location_x,location_y
3940,1,Right Center Back,Regular Play,0,Off T,Open Play,Right Foot,Normal,0,0,"[{'location': [117.5, 42.5], 'player': {'id': ...",0,101.9,58.1
3941,1,Center Forward,Regular Play,0,Goal,Open Play,Right Foot,Backheel,1,0,"[{'location': [111.3, 59.9], 'player': {'id': ...",0,113.8,45.4
3942,1,Center Forward,From Throw In,1,Wayward,Open Play,Head,Normal,0,0,"[{'location': [110.4, 33.0], 'player': {'id': ...",1,116.1,38.6
3943,1,Right Center Midfield,Regular Play,0,Blocked,Open Play,Left Foot,Normal,0,0,"[{'location': [102.5, 36.9], 'player': {'id': ...",0,103.1,35.5
3944,1,Center Forward,From Free Kick,0,Off T,Free Kick,Right Foot,Normal,0,0,"[{'location': [117.6, 39.9], 'player': {'id': ...",0,90.9,34.5
3945,1,Left Center Midfield,From Free Kick,0,Goal,Free Kick,Right Foot,Normal,0,1,"[{'location': [109.5, 31.7], 'player': {'id': ...",0,101.0,27.2
3946,1,Right Midfield,Regular Play,0,Post,Open Play,Right Foot,Normal,0,0,"[{'location': [108.0, 38.9], 'player': {'id': ...",0,107.3,53.4
3947,1,Right Back,Regular Play,0,Saved,Open Play,Right Foot,Half Volley,1,0,"[{'location': [115.9, 43.7], 'player': {'id': ...",0,105.9,42.4
3948,1,Right Midfield,From Corner,0,Blocked,Open Play,Right Foot,Volley,1,0,"[{'location': [95.2, 34.6], 'player': {'id': 5...",0,96.2,47.9
3949,1,Right Center Back,From Corner,0,Blocked,Open Play,Right Foot,Half Volley,1,0,"[{'location': [106.7, 34.2], 'player': {'id': ...",0,108.6,41.4
3950,1,Center Forward,Regular Play,0,Blocked,Open Play,Left Foot,Normal,0,0,"[{'location': [105.2, 50.4], 'player': {'id': ...",0,94.9,46.8
3951,1,Right Wing,Regular Play,0,Blocked,Open Play,Left Foot,Normal,0,0,"[{'location': [102.8, 32.4], 'player': {'id': ...",0,99.8,33.8
3952,1,Right Wing,From Throw In,0,Blocked,Open Play,Left Foot,Normal,0,0,"[{'location': [108.0, 45.9], 'player': {'id': ...",0,112.8,24.6
3953,1,Right Wing,From Corner,0,Saved,Open Play,Left Foot,Half Volley,0,0,"[{'location': [118.5, 38.1], 'player': {'id': ...",0,117.0,47.2
3954,2,Right Wing,Regular Play,0,Blocked,Open Play,Left Foot,Normal,1,0,"[{'location': [108.1, 27.5], 'player': {'id': ...",0,114.1,32.7
3955,2,Left Center Midfield,Regular Play,0,Off T,Open Play,Right Foot,Normal,1,0,"[{'location': [96.5, 51.4], 'player': {'id': 8...",0,93.8,41.8
3956,2,Center Forward,Regular Play,0,Off T,Open Play,Left Foot,Normal,0,0,"[{'location': [98.8, 41.7], 'player': {'id': 5...",0,101.3,30.6
3957,2,Right Center Back,Regular Play,0,Goal,Open Play,Right Foot,Half Volley,1,0,"[{'location': [111.9, 43.1], 'player': {'id': ...",0,110.6,39.8
3958,2,Right Center Forward,From Free Kick,0,Blocked,Free Kick,Left Foot,Normal,0,0,"[{'location': [99.6, 34.9], 'player': {'id': 5...",0,90.5,35.5
3959,2,Left Center Midfield,From Free Kick,0,Wayward,Open Play,Head,Normal,0,0,"[{'location': [117.6, 39.8], 'player': {'id': ...",0,112.2,43.1
3960,2,Right Center Forward,From Free Kick,0,Blocked,Free Kick,Left Foot,Normal,0,0,"[{'location': [106.7, 36.6], 'player': {'id': ...",0,97.2,34.9
3961,2,Right Center Back,Regular Play,1,Wayward,Open Play,Right Foot,Normal,0,0,"[{'location': [109.4, 33.0], 'player': {'id': ...",0,113.6,56.5
3962,2,Center Back,From Throw In,0,Saved,Open Play,Head,Normal,0,0,"[{'location': [112.3, 34.2], 'player': {'id': ...",0,112.1,32.9
3963,2,Left Center Midfield,From Corner,0,Blocked,Open Play,Right Foot,Normal,1,0,"[{'location': [105.6, 55.9], 'player': {'id': ...",0,103.6,40.4
3964,2,Left Midfield,From Corner,0,Off T,Open Play,Left Foot,Half Volley,1,0,"[{'location': [101.4, 50.2], 'player': {'id': ...",0,102.2,29.5
3965,2,Left Center Midfield,From Throw In,0,Off T,Open Play,Right Foot,Half Volley,1,0,"[{'location': [111.4, 39.5], 'player': {'id': ...",0,102.3,49.2
3966,2,Right Center Forward,From Free Kick,0,Saved,Free Kick,Left Foot,Normal,0,0,"[{'location': [106.5, 36.0], 'player': {'id': ...",0,98.3,52.5
3967,2,Center Back,From Goal Kick,1,Off T,Open Play,Right Foot,Normal,1,0,"[{'location': [102.9, 48.1], 'player': {'id': ...",0,101.3,29.1
3968,2,Left Center Forward,Regular Play,0,Off T,Open Play,Head,Normal,0,0,"[{'location': [117.7, 38.1], 'player': {'id': ...",0,109.4,31.2
3969,2,Center Back,From Free Kick,1,Blocked,Open Play,Right Foot,Volley,1,0,"[{'location': [99.1, 43.4], 'player': {'id': 2...",0,108.1,39.1
3970,2,Goalkeeper,From Free Kick,0,Blocked,Open Play,Right Foot,Half Volley,1,0,"[{'location': [94.9, 40.2], 'player': {'id': 5...",0,102.0,41.1
3971,2,Left Wing Back,From Free Kick,0,Off T,Open Play,Left Foot,Volley,1,0,"[{'location': [107.7, 35.9], 'player': {'id': ...",0,100.6,33.2

In [67]:
is_goal = (el_classico_clean['shot_outcome'] == 'Goal').astype(int)
el_classico_clean.loc[:, 'is_goal'] = is_goal
el_classico_clean = el_classico_clean.drop(columns=['shot_outcome'])
el_classico_clean

,period,position,play_pattern,under_pressure,shot_type,shot_body_part,shot_technique,shot_first_time,shot_deflected,shot_freeze_frame,shot_aerial_won,location_x,location_y,is_goal
3940,1,Right Center Back,Regular Play,0,Open Play,Right Foot,Normal,0,0,"[{'location': [117.5, 42.5], 'player': {'id': ...",0,101.9,58.1,0
3941,1,Center Forward,Regular Play,0,Open Play,Right Foot,Backheel,1,0,"[{'location': [111.3, 59.9], 'player': {'id': ...",0,113.8,45.4,1
3942,1,Center Forward,From Throw In,1,Open Play,Head,Normal,0,0,"[{'location': [110.4, 33.0], 'player': {'id': ...",1,116.1,38.6,0
3943,1,Right Center Midfield,Regular Play,0,Open Play,Left Foot,Normal,0,0,"[{'location': [102.5, 36.9], 'player': {'id': ...",0,103.1,35.5,0
3944,1,Center Forward,From Free Kick,0,Free Kick,Right Foot,Normal,0,0,"[{'location': [117.6, 39.9], 'player': {'id': ...",0,90.9,34.5,0
3945,1,Left Center Midfield,From Free Kick,0,Free Kick,Right Foot,Normal,0,1,"[{'location': [109.5, 31.7], 'player': {'id': ...",0,101.0,27.2,1
3946,1,Right Midfield,Regular Play,0,Open Play,Right Foot,Normal,0,0,"[{'location': [108.0, 38.9], 'player': {'id': ...",0,107.3,53.4,0
3947,1,Right Back,Regular Play,0,Open Play,Right Foot,Half Volley,1,0,"[{'location': [115.9, 43.7], 'player': {'id': ...",0,105.9,42.4,0
3948,1,Right Midfield,From Corner,0,Open Play,Right Foot,Volley,1,0,"[{'location': [95.2, 34.6], 'player': {'id': 5...",0,96.2,47.9,0
3949,1,Right Center Back,From Corner,0,Open Play,Right Foot,Half Volley,1,0,"[{'location': [106.7, 34.2], 'player': {'id': ...",0,108.6,41.4,0
3950,1,Center Forward,Regular Play,0,Open Play,Left Foot,Normal,0,0,"[{'location': [105.2, 50.4], 'player': {'id': ...",0,94.9,46.8,0
3951,1,Right Wing,Regular Play,0,Open Play,Left Foot,Normal,0,0,"[{'location': [102.8, 32.4], 'player': {'id': ...",0,99.8,33.8,0
3952,1,Right Wing,From Throw In,0,Open Play,Left Foot,Normal,0,0,"[{'location': [108.0, 45.9], 'player': {'id': ...",0,112.8,24.6,0
3953,1,Right Wing,From Corner,0,Open Play,Left Foot,Half Volley,0,0,"[{'location': [118.5, 38.1], 'player': {'id': ...",0,117.0,47.2,0
3954,2,Right Wing,Regular Play,0,Open Play,Left Foot,Normal,1,0,"[{'location': [108.1, 27.5], 'player': {'id': ...",0,114.1,32.7,0
3955,2,Left Center Midfield,Regular Play,0,Open Play,Right Foot,Normal,1,0,"[{'location': [96.5, 51.4], 'player': {'id': 8...",0,93.8,41.8,0
3956,2,Center Forward,Regular Play,0,Open Play,Left Foot,Normal,0,0,"[{'location': [98.8, 41.7], 'player': {'id': 5...",0,101.3,30.6,0
3957,2,Right Center Back,Regular Play,0,Open Play,Right Foot,Half Volley,1,0,"[{'location': [111.9, 43.1], 'player': {'id': ...",0,110.6,39.8,1
3958,2,Right Center Forward,From Free Kick,0,Free Kick,Left Foot,Normal,0,0,"[{'location': [99.6, 34.9], 'player': {'id': 5...",0,90.5,35.5,0
3959,2,Left Center Midfield,From Free Kick,0,Open Play,Head,Normal,0,0,"[{'location': [117.6, 39.8], 'player': {'id': ...",0,112.2,43.1,0
3960,2,Right Center Forward,From Free Kick,0,Free Kick,Left Foot,Normal,0,0,"[{'location': [106.7, 36.6], 'player': {'id': ...",0,97.2,34.9,0
3961,2,Right Center Back,Regular Play,1,Open Play,Right Foot,Normal,0,0,"[{'location': [109.4, 33.0], 'player': {'id': ...",0,113.6,56.5,0
3962,2,Center Back,From Throw In,0,Open Play,Head,Normal,0,0,"[{'location': [112.3, 34.2], 'player': {'id': ...",0,112.1,32.9,0
3963,2,Left Center Midfield,From Corner,0,Open Play,Right Foot,Normal,1,0,"[{'location': [105.6, 55.9], 'player': {'id': ...",0,103.6,40.4,0
3964,2,Left Midfield,From Corner,0,Open Play,Left Foot,Half Volley,1,0,"[{'location': [101.4, 50.2], 'player': {'id': ...",0,102.2,29.5,0
3965,2,Left Center Midfield,From Throw In,0,Open Play,Right Foot,Half Volley,1,0,"[{'location': [111.4, 39.5], 'player': {'id': ...",0,102.3,49.2,0
3966,2,Right Center Forward,From Free Kick,0,Free Kick,Left Foot,Normal,0,0,"[{'location': [106.5, 36.0], 'player': {'id': ...",0,98.3,52.5,0
3967,2,Center Back,From Goal Kick,1,Open Play,Right Foot,Normal,1,0,"[{'location': [102.9, 48.1], 'player': {'id': ...",0,101.3,29.1,0
3968,2,Left Center Forward,Regular Play,0,Open Play,Head,Normal,0,0,"[{'location': [117.7, 38.1], 'player': {'id': ...",0,109.4,31.2,0
3969,2,Center Back,From Free Kick,1,Open Play,Right Foot,Volley,1,0,"[{'location': [99.1, 43.4], 'player': {'id': 2...",0,108.1,39.1,0
3970,2,Goalkeeper,From Free Kick,0,Open Play,Right Foot,Half Volley,1,0,"[{'location': [94.9, 40.2], 'player': {'id': 5...",0,102.0,41.1,0
3971,2,Left Wing Back,From Free Kick,0,Open Play,Left Foot,Volley,1,0,"[{'location': [107.7, 35.9], 'player': {'id': ...",0,100.6,33.2,0

In [69]:
encoded = pd.get_dummies(el_classico_clean, columns=['position', 'play_pattern', 'shot_type', 'shot_body_part', 'shot_technique'],dtype=int, drop_first=True)
encoded

,period,under_pressure,shot_first_time,shot_deflected,shot_freeze_frame,shot_aerial_won,location_x,location_y,is_goal,position_Center Forward,...,play_pattern_From Free Kick,play_pattern_From Goal Kick,play_pattern_From Throw In,play_pattern_Regular Play,shot_type_Open Play,shot_body_part_Left Foot,shot_body_part_Right Foot,shot_technique_Half Volley,shot_technique_Normal,shot_technique_Volley
3940,1,0,0,0,"[{'location': [117.5, 42.5], 'player': {'id': ...",0,101.9,58.1,0,0,...,0,0,0,1,1,0,1,0,1,0
3941,1,0,1,0,"[{'location': [111.3, 59.9], 'player': {'id': ...",0,113.8,45.4,1,1,...,0,0,0,1,1,0,1,0,0,0
3942,1,1,0,0,"[{'location': [110.4, 33.0], 'player': {'id': ...",1,116.1,38.6,0,1,...,0,0,1,0,1,0,0,0,1,0
3943,1,0,0,0,"[{'location': [102.5, 36.9], 'player': {'id': ...",0,103.1,35.5,0,0,...,0,0,0,1,1,1,0,0,1,0
3944,1,0,0,0,"[{'location': [117.6, 39.9], 'player': {'id': ...",0,90.9,34.5,0,1,...,1,0,0,0,0,0,1,0,1,0
3945,1,0,0,1,"[{'location': [109.5, 31.7], 'player': {'id': ...",0,101.0,27.2,1,0,...,1,0,0,0,0,0,1,0,1,0
3946,1,0,0,0,"[{'location': [108.0, 38.9], 'player': {'id': ...",0,107.3,53.4,0,0,...,0,0,0,1,1,0,1,0,1,0
3947,1,0,1,0,"[{'location': [115.9, 43.7], 'player': {'id': ...",0,105.9,42.4,0,0,...,0,0,0,1,1,0,1,1,0,0
3948,1,0,1,0,"[{'location': [95.2, 34.6], 'player': {'id': 5...",0,96.2,47.9,0,0,...,0,0,0,0,1,0,1,0,0,1
3949,1,0,1,0,"[{'location': [106.7, 34.2], 'player': {'id': ...",0,108.6,41.4,0,0,...,0,0,0,0,1,0,1,1,0,0
3950,1,0,0,0,"[{'location': [105.2, 50.4], 'player': {'id': ...",0,94.9,46.8,0,1,...,0,0,0,1,1,1,0,0,1,0
3951,1,0,0,0,"[{'location': [102.8, 32.4], 'player': {'id': ...",0,99.8,33.8,0,0,...,0,0,0,1,1,1,0,0,1,0
3952,1,0,0,0,"[{'location': [108.0, 45.9], 'player': {'id': ...",0,112.8,24.6,0,0,...,0,0,1,0,1,1,0,0,1,0
3953,1,0,0,0,"[{'location': [118.5, 38.1], 'player': {'id': ...",0,117.0,47.2,0,0,...,0,0,0,0,1,1,0,1,0,0
3954,2,0,1,0,"[{'location': [108.1, 27.5], 'player': {'id': ...",0,114.1,32.7,0,0,...,0,0,0,1,1,1,0,0,1,0
3955,2,0,1,0,"[{'location': [96.5, 51.4], 'player': {'id': 8...",0,93.8,41.8,0,0,...,0,0,0,1,1,0,1,0,1,0
3956,2,0,0,0,"[{'location': [98.8, 41.7], 'player': {'id': 5...",0,101.3,30.6,0,1,...,0,0,0,1,1,1,0,0,1,0
3957,2,0,1,0,"[{'location': [111.9, 43.1], 'player': {'id': ...",0,110.6,39.8,1,0,...,0,0,0,1,1,0,1,1,0,0
3958,2,0,0,0,"[{'location': [99.6, 34.9], 'player': {'id': 5...",0,90.5,35.5,0,0,...,1,0,0,0,0,1,0,0,1,0
3959,2,0,0,0,"[{'location': [117.6, 39.8], 'player': {'id': ...",0,112.2,43.1,0,0,...,1,0,0,0,1,0,0,0,1,0
3960,2,0,0,0,"[{'location': [106.7, 36.6], 'player': {'id': ...",0,97.2,34.9,0,0,...,1,0,0,0,0,1,0,0,1,0
3961,2,1,0,0,"[{'location': [109.4, 33.0], 'player': {'id': ...",0,113.6,56.5,0,0,...,0,0,0,1,1,0,1,0,1,0
3962,2,0,0,0,"[{'location': [112.3, 34.2], 'player': {'id': ...",0,112.1,32.9,0,0,...,0,0,1,0,1,0,0,0,1,0
3963,2,0,1,0,"[{'location': [105.6, 55.9], 'player': {'id': ...",0,103.6,40.4,0,0,...,0,0,0,0,1,0,1,0,1,0
3964,2,0,1,0,"[{'location': [101.4, 50.2], 'player': {'id': ...",0,102.2,29.5,0,0,...,0,0,0,0,1,1,0,1,0,0
3965,2,0,1,0,"[{'location': [111.4, 39.5], 'player': {'id': ...",0,102.3,49.2,0,0,...,0,0,1,0,1,0,1,1,0,0
3966,2,0,0,0,"[{'location': [106.5, 36.0], 'player': {'id': ...",0,98.3,52.5,0,0,...,1,0,0,0,0,1,0,0,1,0
3967,2,1,1,0,"[{'location': [102.9, 48.1], 'player': {'id': ...",0,101.3,29.1,0,0,...,0,1,0,0,1,0,1,0,1,0
3968,2,0,0,0,"[{'location': [117.7, 38.1], 'player': {'id': ...",0,109.4,31.2,0,0,...,0,0,0,1,1,0,0,0,1,0
3969,2,1,1,0,"[{'location': [99.1, 43.4], 'player': {'id': 2...",0,108.1,39.1,0,0,...,1,0,0,0,1,0,1,0,0,1
3970,2,0,1,0,"[{'location': [94.9, 40.2], 'player': {'id': 5...",0,102.0,41.1,0,0,...,1,0,0,0,1,0,1,1,0,0
3971,2,0,1,0,"[{'location': [107.7, 35.9], 'player': {'id': ...",0,100.6,33.2,0,0,...,1,0,0,0,1,1,0,0,0,1